Repository Ensembl/ensembl-production, pull requests merged in 2019-04, with the labels that each got.

#249 Ontologies names now uppercase
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/OLSLoadAll_conf.pm
Labels: bugfix

#250 Disabled flush and lock for all the mart databases. The gene mart now…
  modules/Bio/EnsEMBL/Production/Utils/CopyDatabase.pm
  modules/Bio/EnsEMBL/Production/Utils/MySQLDumping.sh
Labels: bugfix

#251 Checking that the target table name doesn't exceed the 64 characters …
  modules/Bio/EnsEMBL/Production/Pipeline/CopyDatabases/CopyDatabaseHive.pm
  modules/Bio/EnsEMBL/Production/Utils/CopyDatabase.pm
Labels: enhancement

#253 Cleaning up the script
  scripts/production_database/analysis_desc_from_prod.pl
Labels: enhancement

#252 ls -1 doesn't work in a directory with too many files: Argument list …
  modules/Bio/EnsEMBL/Production/Utils/MySQLDumping.sh
Labels: enhancement

#258 staging_dir variable was used before being defined so the script did …
  modules/Bio/EnsEMBL/Production/Utils/CopyDatabase.pm
Labels: bugfix

#247 Retired eg flag, eg-release, previous_release, eg_version and sub_dir…
  modules/Bio/EnsEMBL/Production/Pipeline/Chainfile/DumpFile.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Common/Base.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FASTA/Base.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FASTA/BlastConverter.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FASTA/BlastIndexer.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FASTA/BlatIndexer.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FASTA/ConcatFiles.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FASTA/CopyDNA.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FASTA/DumpFile.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FASTA/FindDirs.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Flatfile/Base.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Flatfile/ChecksumGenerator.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Flatfile/DumpFile.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Flatfile/FindDirs.pm
  modules/Bio/EnsEMBL/Production/Pipeline/GFF3/Base.pm
  modules/Bio/EnsEMBL/Production/Pipeline/GFF3/ChecksumGenerator.pm
  modules/Bio/EnsEMBL/Production/Pipeline/GFF3/DumpFile.pm
  modules/Bio/EnsEMBL/Production/Pipeline/GTF/Base.pm
  modules/Bio/EnsEMBL/Production/Pipeline/GTF/ChecksumGenerator.pm
  modules/Bio/EnsEMBL/Production/Pipeline/GTF/DumpFile.pm
  modules/Bio/EnsEMBL/Production/Pipeline/JSON/DumpGenomeJson.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_non_vertebrates_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_vertebrates_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/RDF/RDFDump.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/BaseDumpJson.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/DumpMerge.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/DumpProbesJson.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/DumpProbesMerge.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/DumpStructuralVariantJson.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/DumpVariantJson.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/ReformatGenomeAdvancedSearch.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/ReformatGenomeEBeye.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/ReformatGenomeSolr.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/ReformatPhenotypesSolr.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/ReformatProbeSetsSolr.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/ReformatProbesSolr.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/ReformatRegulationSolr.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/ReformatStructuralVariantsSolr.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/ReformatVariantsAdvancedSearch.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/ReformatVariantsEBeye.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/ReformatVariantsSolr.pm
  modules/Bio/EnsEMBL/Production/Pipeline/TSV/Base.pm
  modules/Bio/EnsEMBL/Production/Pipeline/TSV/DumpFile.pm
  modules/Bio/EnsEMBL/Production/Pipeline/TSV/DumpFileEna.pm
  modules/Bio/EnsEMBL/Production/Pipeline/TSV/DumpFileMetadata.pm
  modules/Bio/EnsEMBL/Production/Pipeline/TSV/DumpFileXref.pm
  modules/t/ebeye_pipeline.t
Labels: enhancement

#261 Adding analysis_capacity values for mapping modules.
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/Xref_update_conf.pm
Labels: enhancement

#263 Updated script to use ensembl_metadata instead of ensembl-production …
  scripts/production_database/populate_species_meta.pl
Labels: bugfix

#264 updating the farm queue
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/Base_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/CopyDatabase_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/CoreStatistics_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DBCopyPatch_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpGenomeJson_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpOrtholog_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/EBeye_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FactoryTest_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FtpChecker_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GPAD_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/LoadFamily_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/MySQLDumping_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/OLSLoad_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/PostCompara_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProteinFeatures_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ReadQueues_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/SearchDumps_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/SearchDumps_non_vert.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/SearchDumps_non_vert_ebeye.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/SearchDumps_vert.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/SearchDumps_vert_ebeye.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/UpdateComparaMemberNamesDescriptions_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/XrefProjection_mouse_strains_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/Xref_update_conf.pm
Labels: bau
