Repository Ensembl/ensembl-production, pull requests merged in 2019-03, with the labels that each got.

#230 Division is always required
  modules/Bio/EnsEMBL/Production/Pipeline/DatabaseDumping/DbDumpingFactory.pm
Labels: enhancement

#231 Automatically checking out release branch for dependant repos when th…
  .travis.yml
Labels: bugfix, enhancement

#234 Update metadata code in production repo using fetch_by_name. This cal…
  modules/Bio/EnsEMBL/Production/Pipeline/JSON/DumpGenomeJson.pm
  modules/Bio/EnsEMBL/Production/Search/AdvancedSearchFormatter.pm
  modules/Bio/EnsEMBL/Production/Search/GenomeFetcher.pm
Labels: bugfix

#219 Updated link to ontology SQL patches files
  scripts/apply_patches.pl
Labels: enhancement

#232 Excluding the Mouse strains from the GPAD load since we don't have GP…
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GPAD_conf.pm
Labels: bugfix

#222 Update script to avoid duplication of the word 'tables' in the legend…
  scripts/sql2html.pl
Labels: bugfix

#221 Rejig structure of Variation Stats pipeline
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/CoreStatistics_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/VariationStatistics_conf.pm
Labels: enhancement

#223 Account for indel variation features with seq_region_start > seq_region_end
  modules/Bio/EnsEMBL/Production/Pipeline/Production/SnpDensity.pm
Labels: bugfix

#233 Updated databases names according to renaming
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/PairAlignerStats_conf.pm
Labels: bugfix

#236 Release/96
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/SearchDumps_non_vert.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/SearchDumps_non_vert_ebeye.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/SearchDumps_vert.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/SearchDumps_vert_ebeye.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/CompressEBeyeXMLFile.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/ReformatGenomeEBeye.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/ValidateXMLFileEBeye.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/WrapGenomeEBeye.pm
  modules/Bio/EnsEMBL/Production/Search/EBeyeGenomeWrapper.pm
Labels: enhancement

#237 Merge release 96
  .travis.yml
  modules/Bio/EnsEMBL/Production/Pipeline/Common/CheckAssemblyGeneset.pm
  modules/Bio/EnsEMBL/Production/Pipeline/CopyDatabases/CopyDatabaseHive.pm
  modules/Bio/EnsEMBL/Production/Pipeline/DatabaseDumping/DbDumpingFactory.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FASTA/Base.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FASTA/CopyDNA.pm
  modules/Bio/EnsEMBL/Production/Pipeline/GPAD/Base.pm
  modules/Bio/EnsEMBL/Production/Pipeline/GPAD/FindFile.pm
  modules/Bio/EnsEMBL/Production/Pipeline/GPAD/LoadFile.pm
  modules/Bio/EnsEMBL/Production/Pipeline/GPAD/ProcessDirectory.pm
  modules/Bio/EnsEMBL/Production/Pipeline/JSON/DumpGenomeJson.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/CoreStatistics_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_eg_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_ensembl_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GPAD_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/PairAlignerStats_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/SearchDumps_non_vert.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/SearchDumps_non_vert_ebeye.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/SearchDumps_vert.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/SearchDumps_vert_ebeye.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/CompressEBeyeXMLFile.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/ReformatGenomeEBeye.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/ValidateXMLFileEBeye.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/WrapGenomeEBeye.pm
  modules/Bio/EnsEMBL/Production/Search/AdvancedSearchFormatter.pm
  modules/Bio/EnsEMBL/Production/Search/EBeyeFormatter.pm
  modules/Bio/EnsEMBL/Production/Search/EBeyeGenomeWrapper.pm
  modules/Bio/EnsEMBL/Production/Search/GenomeFetcher.pm
  modules/Bio/EnsEMBL/Production/Utils/CopyDatabase.pm
  modules/t/45-searchdumps_reformat_ebeye.t
  modules/t/MultiTestDB.conf.default
  modules/t/ebeye_genes_test.xml.expected
  modules/t/ebeye_genome_test.xml.expected
  modules/t/ebeye_sequences_test.xml.expected
  modules/t/ebeye_variants_test.xml.expected
  modules/t/test-genome-DBs/homo_sapiens/core/meta.txt
  modules/t/test-genome-DBs/homo_sapiens/core/table.sql
  modules/t/test-genome-DBs/multi/metadata/assembly.txt
  modules/t/test-genome-DBs/multi/metadata/data_release.txt
  modules/t/test-genome-DBs/multi/metadata/division.txt
  modules/t/test-genome-DBs/multi/metadata/genome.txt
  modules/t/test-genome-DBs/multi/metadata/organism.txt
  modules/t/test-genome-DBs/multi/metadata/table.sql
  modules/t/test-genome-DBs/multi/production/meta.txt
  modules/t/test-genome-DBs/multi/production/table.sql
  sql/patch_95_96_a.sql
  travisci/harness.sh
Labels: bau

#240 Merge merge release 96
  modules/Bio/EnsEMBL/Production/Utils/MySQLDumping.sh
Labels: bugfix

#241 Removing the database directory for a fresh dump makes the script fai…
  modules/Bio/EnsEMBL/Production/Utils/MySQLDumping.sh
Labels: enhancement

#243 Also checking for pipes errors
  modules/Bio/EnsEMBL/Production/Utils/MySQLDumping.sh
Labels: bugfix

#245 Old version number used in sql patch
  sql/patch_96_97_a.sql
Labels: bugfix

#246 Removed species dependency, fixed SQL calls matching the new producti…
  scripts/production_database/analysis_desc_from_prod.pl
Labels: enhancement
