Repository Ensembl/ensembl-production, pull requests merged in 2019-10, with the labels that each got.

#344 Fixed issues where checksum_generator analysis was trying to generate…
  modules/Bio/EnsEMBL/Production/Pipeline/Common/ChksumGenerator.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FASTA/BlatIndexer.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_non_vertebrates_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_vertebrates_conf.pm
Labels: bugfix, enhancement

#345 Bugfix/99 null replacement in field
  modules/Bio/EnsEMBL/Production/Utils/MySQLDumping.sh
Labels: bugfix

#346 Updated My6SQL dumping pipeline to add CHECKSUM separated step (allow…
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/MySQLDumping_conf.pm
  modules/Bio/EnsEMBL/Production/Utils/MySQLDumping.sh
Labels: enhancement

#347 Need to dump DNA if there is a geneset update
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
Labels: bugfix

#348 Prevent creation of tsv files if there is no data.
  modules/Bio/EnsEMBL/Production/Pipeline/TSV/DumpFileEna.pm
  modules/Bio/EnsEMBL/Production/Pipeline/TSV/DumpFileMetadata.pm
  modules/Bio/EnsEMBL/Production/Pipeline/TSV/DumpFileXref.pm
Labels: bugfix

#351 Added Sed command to replace Windows \r chars by "nothing". hence cle…
  modules/Bio/EnsEMBL/Production/Utils/MySQLDumping.sh
Labels: bugfix, enhancement

#350 Adding new option skip_optimize to allow user to skip the optimizatio…
  modules/Bio/EnsEMBL/Production/Pipeline/CopyDatabases/CopyDatabaseHive.pm
  modules/Bio/EnsEMBL/Production/Utils/CopyDatabase.pm
  scripts/copy_database.pl
Labels: enhancement

#349 External DB Type now not null field
  sql/patch_98_99_b.sql
  sql/table.sql
Labels: enhancement
