Repository Ensembl/ensembl-production, pull requests merged in 2019-11, with the labels that each got.

#354 Fix FASTA::ConcatFiles bgzip regex
  modules/Bio/EnsEMBL/Production/Pipeline/FASTA/ConcatFiles.pm
Labels: bugfix

#355 Added Validation and compression steps for the ebeye Variants and wra…
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/SearchDumps_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/SearchDumps_ebeye_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/CompressEBeyeXMLFile.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/ReformatVariantsEBeye.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/ValidateXMLFileEBeye.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/WrapGenomeEBeye.pm
Labels: bugfix, enhancement

#356 Prefixing ebeye dumps to reduce Web team post handover work
  modules/Bio/EnsEMBL/Production/Pipeline/Search/ReformatGenomeEBeye.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/ReformatVariantsEBeye.pm
Labels: enhancement

#357 Disabled SOLR reformat since nobody uses them at the moment. Disabled…
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/SearchDumps_conf.pm
Labels: enhancement

#358 Removing code silently skipping blocks over 5000000 and increasing hi…
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/CoreStatistics_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Production/PercentRepeat.pm
Labels: bugfix

#359 Slight change to the logic of the DbFactory
  modules/Bio/EnsEMBL/Production/Pipeline/Common/DbFactory.pm
Labels: bugfix
