Repository Ensembl/ensembl-production, pull requests merged in 2019-07, with the labels that each got.

#296 Blat update
  modules/Bio/EnsEMBL/Production/Pipeline/FASTA/BlatIndexer.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_vertebrates_conf.pm
Labels: enhancement

#297 Renaming variation.source.database meta key to match new name variati…
  modules/Bio/EnsEMBL/Production/Pipeline/Common/SpeciesFactory.pm
Labels: bau

#298 Fix datachecks for variation statistics pipeline
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/VariationStatistics_conf.pm
Labels: bugfix

#299 lates_calcarifer should not be in the BLAT list
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
Labels: bugfix

#300 Assembly converter linkout update
  scripts/assembly_converter/populate_assembly_converter_dir.sh
Labels: bau

#302 Updating protein features pipeline config for latest interpro version
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProteinFeatures_conf.pm
Labels: bau

#303 Feature/stable ids gene autocomplete pipe
  modules/Bio/EnsEMBL/Production/Pipeline/GeneAutocomplete/CreateGeneAutoComplete.pm
  modules/Bio/EnsEMBL/Production/Pipeline/GeneAutocomplete/sql/table.sql
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GeneAutoComplete_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/OLSLoad_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/StableIDs_conf.pm
Labels: bau

#304 Get correct name for previous release database
  scripts/update_mapping_set.pl
Labels: bugfix

#305 apply_patches.pl: Update location of ontology schema
  scripts/apply_patches.pl
Labels: bau
