Repository Ensembl/ensembl-production, pull requests merged in 2019-09, with the labels that each got.

#318 Refactoring gene name/description projection pipeline
  modules/Bio/EnsEMBL/Production/Pipeline/GeneNameDescProjection/Base.pm
  modules/Bio/EnsEMBL/Production/Pipeline/GeneNameDescProjection/DeleteExisting.pm
  modules/Bio/EnsEMBL/Production/Pipeline/GeneNameDescProjection/GeneDescProjection.pm
  modules/Bio/EnsEMBL/Production/Pipeline/GeneNameDescProjection/GeneNamesEmailReport.pm
  modules/Bio/EnsEMBL/Production/Pipeline/GeneNameDescProjection/GeneNamesProjection.pm
  modules/Bio/EnsEMBL/Production/Pipeline/GeneNameDescProjection/SourceFactory.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/Base_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GeneNameDescProjection_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GeneNameDescProjection_mouse_strains_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GeneNameDescProjection_plants_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GeneNameDescProjection_protists_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GeneNameDescProjection_vertebrates_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/PostCompara_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/PostCompara_conf_fungi.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/PostCompara_conf_metazoa.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/PostCompara_conf_plants.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/PostCompara_conf_protists.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/XrefProjection_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/XrefProjection_mouse_strains_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PostCompara/DumpingCleaningSetup.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PostCompara/GOEmailReport.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PostCompara/GOProjection.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PostCompara/GOProjectionSourceFactory.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PostCompara/GeneCoverage.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PostCompara/GeneCoverageEmailReport.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PostCompara/GeneCoverageFactory.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PostCompara/GeneDescProjection.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PostCompara/GeneNamesProjection.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PostCompara/GeneNamesProjectionSourceFactory.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PostCompara/NotifyUser.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PostCompara/RestoreBackups.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PostCompara/TblCleanup.pm
Labels: bugfix, enhancement

#320 Re-applied fix from release/98
  modules/Bio/EnsEMBL/Production/Utils/MySQLDumping.sh
Labels: bugfix

#321 We don't dump the MTMP_* mart temp table so we should not check if th…
  modules/Bio/EnsEMBL/Production/Pipeline/DatabaseDumping/MySQLDumpsCheck.pm
Labels: bugfix

#322 If we get an error from the mysql command, the script doesn't return …
  modules/Bio/EnsEMBL/Production/Utils/MySQLDumping.sh
Labels: bugfix

#323 Adding mart temporary MTMP tables that exists for GRCh37 human and so…
  modules/Bio/EnsEMBL/Production/Utils/MySQLDumping.sh
Labels: enhancement

#324 Explicit disconnect for slice function, to prevent lost db connection for RDF dumps
  modules/Bio/EnsEMBL/Production/Pipeline/Common/Base.pm
Labels: bugfix

#327 MySQL dumps for the pan division should go under pan_ensembl and not …
  modules/Bio/EnsEMBL/Production/Pipeline/DatabaseDumping/DbDumpingFactory.pm
Labels: bugfix

#325 Moved the executable checks to only run them on server where we can s…
  modules/Bio/EnsEMBL/Production/Utils/CopyDatabase.pm
Labels: bugfix, enhancement

#319 FTP Dump config tweaks
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_vertebrates_conf.pm
Labels: enhancement

#328 Increased the max allowed packed since it failed for a vert species. …
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/MySQLDumping_conf.pm
  modules/Bio/EnsEMBL/Production/Utils/MySQLDumping.sh
Labels: bugfix

#330 Updated Compara checks to match new changes from Compara for Plants a…
  modules/Bio/EnsEMBL/Production/Pipeline/FtpChecker/CheckComparaFtp.pm
Labels: bugfix

#331 Added Compara emf dumps to the list
  modules/Bio/EnsEMBL/Production/Pipeline/FtpChecker/CheckComparaFtp.pm
Labels: enhancement

#334 Created schema patches for release 99
  sql/patch_98_99_a.sql
  sql/table.sql
Labels: bau

#335 Updated test databases to 99
  modules/t/test-genome-DBs/homo_sapiens_dump/funcgen/meta.txt
  modules/t/test-genome-DBs/homo_sapiens_dump/funcgen/table.sql
Labels: bau

#333 Adding Pepstats datacheck to Protein Features pipeline...
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProteinFeatures_conf.pm
Labels: enhancement

#338 Adding SQL to cleanup orphan dependent_xref since it can happen in so…
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GPAD_conf.pm
Labels: bugfix

#339 We now experience MySQL went away error when copying a large database…
  modules/Bio/EnsEMBL/Production/Utils/CopyDatabase.pm
Labels: enhancement

#340 Fixed problem with pipeline generating empty dir for species without …
  modules/Bio/EnsEMBL/Production/Pipeline/Chainfile/DumpFile.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Common/Base.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Common/ChksumGenerator.pm
  modules/Bio/EnsEMBL/Production/Pipeline/EBeye/Base.pm
  modules/Bio/EnsEMBL/Production/Pipeline/EBeye/ChecksumGenerator.pm
  modules/Bio/EnsEMBL/Production/Pipeline/EBeye/DumpFile.pm
  modules/Bio/EnsEMBL/Production/Pipeline/EBeye/DumpReleaseNotesFile.pm
  modules/Bio/EnsEMBL/Production/Pipeline/EBeye/DumpTypeFactory.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FASTA/Base.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FASTA/BlastConverter.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FASTA/ConcatFiles.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FASTA/CopyDNA.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FASTA/CreatePrimaryAssembly.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FASTA/DumpFile.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FASTA/FindDirs.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Flatfile/Base.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Flatfile/CheckFlatfile.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Flatfile/ChecksumGenerator.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Flatfile/DumpFile.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Flatfile/FindDirs.pm
  modules/Bio/EnsEMBL/Production/Pipeline/GFF3/Base.pm
  modules/Bio/EnsEMBL/Production/Pipeline/GFF3/ChecksumGenerator.pm
  modules/Bio/EnsEMBL/Production/Pipeline/GFF3/DumpFile.pm
  modules/Bio/EnsEMBL/Production/Pipeline/GTF/Base.pm
  modules/Bio/EnsEMBL/Production/Pipeline/GTF/ChecksumGenerator.pm
  modules/Bio/EnsEMBL/Production/Pipeline/GTF/DumpFile.pm
  modules/Bio/EnsEMBL/Production/Pipeline/JSON/DumpGenomeJson.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_non_vertebrates_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/RDF/RDFDump.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/BaseDumpJson.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/ReformatGenomeAdvancedSearch.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/ReformatGenomeEBeye.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/ReformatGenomeSolr.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/ReformatPhenotypesSolr.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/ReformatProbeSetsSolr.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/ReformatProbesAdvancedSearch.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/ReformatProbesSolr.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/ReformatProbesetsAdvancedSearch.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/ReformatRegulationAdvancedSearch.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/ReformatRegulationSolr.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/ReformatStructuralVariantsSolr.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/ReformatVariantsAdvancedSearch.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/ReformatVariantsEBeye.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/ReformatVariantsSolr.pm
  modules/Bio/EnsEMBL/Production/Pipeline/TSV/Base.pm
  modules/Bio/EnsEMBL/Production/Pipeline/TSV/DumpFile.pm
  modules/Bio/EnsEMBL/Production/Pipeline/TSV/DumpFileEna.pm
  modules/Bio/EnsEMBL/Production/Pipeline/TSV/DumpFileXref.pm
  modules/t/ebeye_pipeline.t
  modules/t/fake_ebeye_binaries/xml
  modules/t/fake_ebeye_binaries/xmllint
Labels: bugfix, enhancement

#341 Updated Interproscan version to 76.0
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProteinFeatures_conf.pm
Labels: bau

#343 Increased memory requirement for Xrefs and core statistics
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/CoreStatistics_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/Xref_update_conf.pm
Labels: bau, enhancement
