Repository Ensembl/ensembl-production, pull requests merged in 2019-02, with the labels that each got.

#209 Updated code to use process_division_names fetch_and_set_release from…
  modules/Bio/EnsEMBL/Production/Pipeline/DatabaseDumping/DbDumpingFactory.pm
Labels: enhancement

#210 fix: do not leave temporary dot files around
  scripts/sql2html.pl
Labels: bug

#208 Copy service extend server support
  .travis.yml
  modules/Bio/EnsEMBL/Production/Pipeline/CopyDatabases/CopyDatabaseHive.pm
  modules/Bio/EnsEMBL/Production/Utils/CopyDatabase.pm
Labels: enhancement

#214 Fixing bioperl version to stop problem installing HTS
  .travis.yml
  travisci/harness.sh
Labels: bugfix
