Repository Ensembl/ensembl-production, pull requests merged in 2019-05, with the labels that each got.

#265 Updated code to allow service to only copy some tables when doing a f…
  modules/Bio/EnsEMBL/Production/Utils/CopyDatabase.pm
Labels: bugfix

#266 These changes are related to the following JIRA ticket: https://www.e…
  modules/Bio/EnsEMBL/Production/Utils/CopyDatabase.pm
Labels: enhancement

#267 Handle empty variation db
  modules/Bio/EnsEMBL/Production/Pipeline/Common/SpeciesFactory.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/VariationStatistics_conf.pm
Labels: bau

#269 Added PHI base ontology loading step (skip_phi parameter to skip)
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/OLSLoad_conf.pm
Labels: bugfix

#271 Restoring ability to update a list of table in an existing database r…
  modules/Bio/EnsEMBL/Production/Utils/CopyDatabase.pm
Labels: bugfix

#270 Fixed populate_analysis_description script to match new release 97 pr…
  scripts/production_database/populate_analysis_description.pl
Labels: bugfix

#272 Fixed wrong regex for embl/genbank files since files are splitted by …
  scripts/copy_ftp_release.pl
Labels: bugfix

#274 Added a new option to convert InnoDB tables to MyISAM on the target d…
  modules/Bio/EnsEMBL/Production/Pipeline/CopyDatabases/CopyDatabaseHive.pm
  modules/Bio/EnsEMBL/Production/Utils/CopyDatabase.pm
  scripts/copy_database.pl
Labels: enhancement

#273 Changed Default destination for dump outputs to a less "occupied" one…
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/MySQLDumping_conf.pm
  modules/Bio/EnsEMBL/Production/Utils/MySQLDumping.sh
Labels: enhancement

#275 Updated rsync command to use ciphers when copying over ssh. The rsync …
  modules/Bio/EnsEMBL/Production/Utils/CopyDatabase.pm
Labels: enhancement

#276 Revert "Updated rsync command to use ciphers when copying over ssh. The rsync …"
  modules/Bio/EnsEMBL/Production/Utils/CopyDatabase.pm
Labels: bugfix

#277 Updated Factory to dump into expected directory structure, e.g: /rele…
  modules/Bio/EnsEMBL/Production/Pipeline/DatabaseDumping/DbDumpingFactory.pm
Labels: bau

#280 The param used by SpeciesNoOrthologs was not the right one, as a resu…
  modules/Bio/EnsEMBL/Production/Pipeline/Ortholog/SpeciesNoOrthologs.pm
Labels: bugfix
