Repository Ensembl/ensembl-production, pull requests merged in 2019-06, with the labels that each got.

#281 Minor changes to species factory. Itroduced new 15GB memory and incre…
  modules/Bio/EnsEMBL/Production/Pipeline/Common/SpeciesFactory.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
Labels: bau

#282 Bugfix/search dump variation fetcher
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/SearchDumps_non_vert_ebeye.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/SearchDumps_vert_ebeye.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/DumpGenesJson.pm
  modules/Bio/EnsEMBL/Production/Search/EBeyeGenomeWrapper.pm
  modules/Bio/EnsEMBL/Production/Search/VariationFetcher.pm
  modules/t/18-searchdumps_dumpvariation.t
  modules/t/test-genome-DBs/homo_sapiens_dump/variation/meta.txt
  modules/t/test-genome-DBs/homo_sapiens_dump/variation/table.sql
  modules/t/test-genome-DBs/homo_sapiens_dump/variation/variation.txt
  modules/t/test-genome-DBs/homo_sapiens_dump/variation/variation_feature.txt
Labels: bugfix

#283 Renamed all the analysis to remove the dump_ prefix. We now have json…
  modules/Bio/EnsEMBL/Production/Pipeline/Common/ChksumGenerator.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_non_vertebrates_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_vertebrates_conf.pm
Labels: bugfix

#284 Updated configuration for mysql dumps:
  modules/Bio/EnsEMBL/Production/Pipeline/DatabaseDumping/DbDumpingFactory.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/MySQLDumping_conf.pm
  modules/Bio/EnsEMBL/Production/Utils/MySQLDumping.sh
Labels: bugfix, enhancement

#285 Fixed typo in dataflow_output_id keys
  modules/Bio/EnsEMBL/Production/Pipeline/DatabaseDumping/DbDumpingFactory.pm
Labels: bugfix

#288 Release/97
  modules/Bio/EnsEMBL/Production/Pipeline/DatabaseDumping/DbDumpingFactory.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/MySQLDumping_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/SearchDumps_non_vert_ebeye.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/SearchDumps_vert_ebeye.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Search/DumpGenesJson.pm
  modules/Bio/EnsEMBL/Production/Search/EBeyeGenomeWrapper.pm
  modules/Bio/EnsEMBL/Production/Search/VariationFetcher.pm
  modules/Bio/EnsEMBL/Production/Utils/MySQLDumping.sh
  modules/t/18-searchdumps_dumpvariation.t
  modules/t/test-genome-DBs/homo_sapiens_dump/variation/meta.txt
  modules/t/test-genome-DBs/homo_sapiens_dump/variation/table.sql
  modules/t/test-genome-DBs/homo_sapiens_dump/variation/variation.txt
  modules/t/test-genome-DBs/homo_sapiens_dump/variation/variation_feature.txt
Labels: bau

#289 Updated meta table for release 98 version patch
  sql/patch_97_98_a.sql
Labels: bau

#291 Release/98
  sql/patch_97_98_a.sql
  sql/table.sql
Labels: bau

#287 Features/link out assembly converter
  scripts/assembly_converter/link_out.sh
Labels: enhancement

#292 Added engine to create table so that we can run pipelines on server w…
  modules/Bio/EnsEMBL/Production/Pipeline/OntologiesLoad/AddSubsetMap.pm
  modules/Bio/EnsEMBL/Production/Pipeline/OntologiesLoad/build_ontology_mart.sql
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/OLSLoad_conf.pm
Labels: bugfix

#293 Added new step to sync the external_db data from the ensembl-producti…
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GeneTreeHighlighting_conf.pm
Labels: bau

#294 Removing old VEP dumps hack now that we have a unified FTP layout
  modules/Bio/EnsEMBL/Production/Pipeline/FtpChecker/CheckCoreFtp.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FtpChecker/CheckFtp.pm
Labels: bugfix

#295 Removing old VEP dumps hack now that we have a unified FTP layout
  modules/Bio/EnsEMBL/Production/Pipeline/FtpChecker/CheckCoreFtp.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FtpChecker/CheckFtp.pm
Labels: bugfix
