Repository Ensembl/ensembl-production, pull requests merged in 2020-01, with the labels that each got.

#371 Removing old ebye pipeline and ebye only config of the search dumps
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/EBeye_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/SearchDumps_ebeye_conf.pm
Labels: enhancement

#369 Minor changes to accommodate JSON-format web_data.
  modules/Bio/EnsEMBL/Production/Pipeline/Common/AnalysisSetup.pm
  modules/Bio/EnsEMBL/Production/Pipeline/GeneAutocomplete/CreateGeneAutoComplete.pm
Labels: enhancement

#372 Related to ENSPROD-4305 and ENSPROD-4782. The first change is to only…
  modules/Bio/EnsEMBL/Production/Pipeline/FASTA/CopyNCBIBlastDNA.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_vertebrates_conf.pm
Labels: bugfix, enhancement

#373 Running a flush and lock then mysqldump when we don't have file syste…
  modules/Bio/EnsEMBL/Production/Utils/CopyDatabase.pm
Labels: bugfix

#376 Moving APPRIS/TSL loading script and pipeconfig from the ensembl-anal…
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/TSLsAppris_conf.pm
  scripts/import_appris.pl
  scripts/import_transcript_support_levels.pl
Labels: enhancement

#375 Extending taxons to include two new fishes callorhinchus_milii and er…
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GeneNameDescProjection_vertebrates_conf.pm
Labels: enhancement

#378 Restructuring of the APPRIS/TSL pipeline. Moving away from hardcoded …
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/TSLsAppris_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PostGenebuild/LoadAppris.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PostGenebuild/LoadTsl.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PostGenebuild/ProcessApprisTSLFiles.pm
  scripts/import_appris.pl
  scripts/import_transcript_support_levels.pl
Labels: enhancement

#379 Renamed Dog
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
Labels: bugfix

#380 Protein feature memory
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProteinFeatures_conf.pm
Labels: enhancement
