Repository Ensembl/ensembl-production, pull requests merged in 2020-12, with the labels that each got.

#521 Features/new db copy
  modules/Bio/EnsEMBL/Production/Pipeline/CopyDatabases/CopyDatabaseHive.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/CopyDatabase_conf.pm
  src/python/ensembl/production/hive/ProductionDBCopy.py
Labels: enhancement

#524 Feature/xref schema so terms
  modules/Bio/EnsEMBL/Production/DBSQL/BulkFetcher.pm
  modules/t/11-searchdumps_dumpgenes.t
Labels: enhancement

#508 Bugfix/json dumps is current meta
  modules/Bio/EnsEMBL/Production/Pipeline/JSON/DumpGenomeJson.pm
Labels: bugfix, enhancement

#525 Only run critical datachecks in the 'controlled_tables' group.
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProductionDBSync_conf.pm
Labels: bugfix

#528 added 104 sql patch
  sql/patch_103_104_a.sql
Labels: bau

#533 GFF3 dump - standalone fix
  modules/Bio/EnsEMBL/Production/Pipeline/GFF3/DumpFile.pm
Labels: bugfix

#534 RR file dump pipeline sends emails about missing RNA-seq
  modules/Bio/EnsEMBL/Production/Pipeline/FileDump/RNASeq_Exists.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FileDump/RNASeq_Missing.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FileDump_conf.pm
Labels: enhancement
