Repository Ensembl/ensembl-production, pull requests merged in 2020-03, with the labels that each got.

#388 Because dog was renamed from canis_familiaris to canis_lupus_familiar…
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
Labels: bau

#389 We need to use the displayable value from the production db, rather t…
  modules/Bio/EnsEMBL/Production/Pipeline/Common/AnalysisSetup.pm
Labels: bugfix

#390 Enable dumping pipeline to store datacheck output
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
Labels: enhancement

#392 Prod db sync pipeline
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProductionDBSync_conf.pm
  modules/Bio/EnsEMBL/Production/Utils/ProductionDbUpdater.pm
Labels: bugfix

#383 Add the ability to run datachecks as part of the bulk SQL pipeline.
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/BulkSQL_conf.pm
Labels: enhancement

#394 Fix for RDF dumping losing connection
  modules/Bio/EnsEMBL/Production/Pipeline/RDF/RDFDump.pm
Labels: bugfix

#393 Update to latest InterProScan version
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProteinFeatures_conf.pm
Labels: bau

#395 Add parameter to allow dbnames to be passed to DbFactory
  modules/Bio/EnsEMBL/Production/Pipeline/Common/DbFactory.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FactoryTest_conf.pm
Labels: enhancement

#396 Release/100
  modules/Bio/EnsEMBL/Production/Pipeline/Common/AnalysisSetup.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Common/DbFactory.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProductionDBSync_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/TSLsAppris_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/UpdateComparaMemberNamesDescriptions_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PostGenebuild/LoadAppris.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PostGenebuild/LoadTsl.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PostGenebuild/ProcessApprisTSLFiles.pm
  modules/Bio/EnsEMBL/Production/Pipeline/ProductionDBSync/PopulateAnalysisDescription.pm
  modules/Bio/EnsEMBL/Production/Pipeline/ProductionDBSync/PopulateControlledTables.pm
  modules/Bio/EnsEMBL/Production/Search/EBeyeFormatter.pm
  modules/Bio/EnsEMBL/Production/Utils/ProductionDbUpdater.pm
  modules/t/ebeye_sequences_test.xml.expected
  modules/t/ebeye_variants_test.xml.expected
  scripts/datafiles/build_datafile_ftp_directory.pl
  scripts/import_appris.pl
  scripts/import_transcript_support_levels.pl
  scripts/production_database/README
  scripts/production_database/generate_default_aliases.pl
  scripts/production_database/import_analysis_web_from_core.pl
  scripts/production_database/populate_analysis_description.pl
  scripts/production_database/populate_production_db_tables.pl
  scripts/production_database/update_controlled_tables.pl
  scripts/production_database/update_database_list.pl
Labels: bau

#397 Added schema patches for release 100 and 101
  sql/patch_100_101_a.sql
  sql/patch_99_100_a.sql
  sql/table.sql
Labels: bau

#398 Update tests 101
  modules/t/test-genome-DBs/homo_sapiens/core/meta.txt
  modules/t/test-genome-DBs/homo_sapiens/core/table.sql
  modules/t/test-genome-DBs/hp_dump/core/meta.txt
  modules/t/test-genome-DBs/hp_dump/core/table.sql
  modules/t/test-genome-DBs/hp_dump/funcgen/meta.txt
  modules/t/test-genome-DBs/hp_dump/funcgen/table.sql
  modules/t/test-genome-DBs/hp_dump/variation/meta.txt
  modules/t/test-genome-DBs/hp_dump/variation/table.sql
  modules/t/test-genome-DBs/multi/compara/meta.txt
  modules/t/test-genome-DBs/multi/compara/table.sql
  modules/t/test-genome-DBs/multi/ontology/meta.txt
  modules/t/test-genome-DBs/multi/ontology/table.sql
  modules/t/test-genome-DBs/s_cerevisiae/core/meta.txt
  modules/t/test-genome-DBs/s_cerevisiae/core/table.sql
Labels: bau

#400 Adding cucumis_melo
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/SampleData_non_vertebrates_conf.pm
Labels: bau
