Repository Ensembl/ensembl-production, pull requests merged in 2020-07, with the labels that each got.

#444 ENSCORESW-3196: separate checksum entries by source to avoid cross so…
  modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/Base.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/RNAcentralMapping.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/UniParcMapping.pm
Labels: enhancement

#445 Update interproscan version, which includes a new Pfam release.
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProteinFeatures_conf.pm
Labels: bau

#446 Features/rr convert meta 2 hive species
  scripts/py/meta_hive_species.py
Labels: enhancement

#448 Use datacheck groups relevant to the pipeline
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GPAD_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GeneNameDescProjection_conf.pm
Labels: enhancement

#453 Ensure GO xrefs have a source xref
  modules/Bio/EnsEMBL/Production/Pipeline/GPAD/LoadFile.pm
Labels: bugfix

#454 Updating README files for ftp dumps
  modules/Bio/EnsEMBL/Production/Pipeline/FASTA/DumpFile.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Flatfile/DumpFile.pm
Labels: bugfix
