Repository Ensembl/ensembl-production, pull requests merged in 2020-11, with the labels that each got.

#509 Fix GFF3 tidying/validation in ftp dumping pipeline
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_vertebrates_conf.pm
Labels: bugfix

#510 Fix out-dated GFF3 README
  modules/Bio/EnsEMBL/Production/Pipeline/GFF3/DumpFile.pm
Labels: bugfix

#511 Production DB Sync pipeline: datacheck optimisation
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProductionDBSync_conf.pm
Labels: enhancement

#512 Add explicit disconnects in variant json dumps
  modules/Bio/EnsEMBL/Production/Search/VariationFetcher.pm
Labels: bugfix

#513 Add explicit disconnects in variant json dumps
  modules/Bio/EnsEMBL/Production/Search/VariationFetcher.pm
Labels: bugfix

#517 Removing redundant comments, parameters, and resource classes from TSL/Appris pipeline
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/TSLsAppris_conf.pm
Labels: enhancement

#516 reduce analysis capacity to remove parallel script calls
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/StableIDs_conf.pm
Labels: bugfix

#519 ENSCORESW-3608: DBASS URL change
  modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/xref_sources.json
Labels: bau

#520 Added release parameter to ensembl_genomes_release.
  modules/Bio/EnsEMBL/Production/Pipeline/JSON/DumpGenomeJson.pm
Labels: bugfix

#502 Webdatafile dump2020
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/WebDataFile_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Webdatafile/Contigs.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Webdatafile/GeneAndTranscript.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Webdatafile/GenerateGC.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Webdatafile/GenomeAssemblyInfo.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Webdatafile/GenomeInfo.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Webdatafile/GenomeInfoYml.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Webdatafile/Variation.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Webdatafile/WebdataFile.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Webdatafile/common_files/transcriptsSummary.as
  modules/Bio/EnsEMBL/Production/Pipeline/Webdatafile/lib/ChromReport.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Webdatafile/lib/CoordinateConverter.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Webdatafile/lib/Genome.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Webdatafile/lib/GenomeLookup.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Webdatafile/lib/GenomeReport.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Webdatafile/lib/IndexBed.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Webdatafile/lib/IndexWig.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Webdatafile/lib/variants/VariantsScaler.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Webdatafile/lib/variants/VariationBedWriter.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Webdatafile/lib/variants/variant_categories.json
  modules/Bio/EnsEMBL/Production/Search/GenomeFetcher.pm
Labels: enhancement

#523 Further updates to RR ftp pipeline
  modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Base.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Metadata_JSON.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FileDump/README.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FileDump/README.txt
  modules/Bio/EnsEMBL/Production/Pipeline/FileDump/RNASeq_Exists.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Xref_TSV.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FileDump_conf.pm
Labels: enhancement
