Repository Ensembl/ensembl-production, pull requests merged in 2020-10, with the labels that each got.

#475 EP-5842: Ontology Pipeline DBCopy fix & terms DataChecks
  .gitignore
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/OLSLoadAll_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/OLSLoad_conf.pm
Labels: enhancement

#498 Feature/xref disconnect idle
  modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/Base.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/ParseSource.pm
Labels: enhancement

#500 Add analysis_capacity for the gene autocomplete analysis
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GeneAutoComplete_conf.pm
Labels: bugfix

#499 Bump up memory allocation for core stats pipeline
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/CoreStatistics_conf.pm
Labels: bugfix

#487 New pipeline for doing ftp dumps for Rapid Release.
  modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Assembly_Chain.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Base.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Base_Filetype.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Chromosome_TSV.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FileDump/DumpFactory.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Geneset_EMBL.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Geneset_FASTA.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Geneset_GFF3.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Geneset_GTF.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Genome_FASTA.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FileDump/MySQL_TXT.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FileDump/README.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FileDump/README.txt
  modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Symlink.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Verify.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Xref_TSV.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FileDumpCore_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FileDump_conf.pm
Labels: enhancement

#493 Updated port number for new / updated species assembly.
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
Labels: bau

#505 Config file for Rapid Release dumps for GOA
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpSpeciesForGOA_conf.pm
Labels: bugfix

#504 Adapt GPAD loading pipeline for use in Rapid Release
  modules/Bio/EnsEMBL/Production/Pipeline/GPAD/Base.pm
  modules/Bio/EnsEMBL/Production/Pipeline/GPAD/FindFile.pm
  modules/Bio/EnsEMBL/Production/Pipeline/GPAD/LoadFile.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/GPAD_conf.pm
Labels: enhancement
