Repository Ensembl/ensembl-production, pull requests merged in 2020-09, with the labels that each got.

#467 Deprecate RDF dumps
  conf/xref_LOD_mapping.json
  conf/xref_LOD_schema.json
  modules/Bio/EnsEMBL/Production/Pipeline/FtpChecker/CheckCoreFtp.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_non_vertebrates_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/RDF/RDFDump.pm
  modules/Bio/EnsEMBL/Production/Pipeline/RDF/ValidateRDF.pm
  scripts/rdf/github.py
  scripts/rdf/project_ftp.py
  scripts/rdf/release_void_file.py
  scripts/rdf/void_rdf.cfg
  scripts/rdf/void_rdf.py
Labels: enhancement

#473 Add option for Production DB sync pipeline to send an email on completion
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProductionDBSync_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/ProductionDBSync/EmailReport.pm
Labels: enhancement

#479 cds data added to search dumps; translation key added to search dumps
  modules/Bio/EnsEMBL/Production/DBSQL/BulkFetcher.pm
Labels: bugfix, enhancement

#480 Add cds to search dumps
  modules/Bio/EnsEMBL/Production/DBSQL/BulkFetcher.pm
Labels: bugfix, enhancement

#476 Non-core synchronisation datacheck pipeline
  modules/Bio/EnsEMBL/Production/Pipeline/Common/DbFactory.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DataChecksNonCore_conf.pm
Labels: enhancement

#477 Add duplicate report to Stable ID pipeline
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/StableIDs_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/StableID/EmailReport.pm
Labels: enhancement

#483 Fix copy script to produce non-truncated GVF and VCF files
  scripts/copy_ftp_release.pl
Labels: bugfix

#481 ENSCORESW-3554: run RefSeq dependent ZFIN parsing last
  modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/xref_sources.json
Labels: bau

#490 Wrappers for the VEP and GVF/VCF pipelines
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FileDumpVEP_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FileDumpVariation_conf.pm
Labels: enhancement

#486 Base decision-making in Core Stats pipeline on datachecks
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/CoreStatistics_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Production/EmailSummaryCore.pm
Labels: bugfix

#491 For release 102 only, we need to replace \r characters in three tables.
  modules/Bio/EnsEMBL/Production/Utils/MySQLDumping.sh
Labels: bugfix
