Repository Ensembl/ensembl-production, pull requests merged in 2021-01, with the labels that each got.

#537 fix Stable Ids Index creation sql command
  modules/Bio/EnsEMBL/Production/Pipeline/StableID/sql/index.sql
Labels: bugfix

#539 Update script to dump three files into HOME:
  scripts/py/meta_hive_species.py
Labels: bau, enhancement

#543 Updated default mail to ensembl-production@ebi.ac.uk where necessary/…
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/Base_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpVariation_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ReadQueues_conf.pm
Labels: enhancement

#540 Bau/merge release104
  modules/Bio/EnsEMBL/Production/Pipeline/GFF3/DumpFile.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProteinFeatures_conf.pm
Labels: bau

#541 Protein Features pipeline - partial annotation and xrefs
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ProteinFeatures_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/ProteinFeatures/AnalysisConfiguration.pm
  modules/Bio/EnsEMBL/Production/Pipeline/ProteinFeatures/ChecksumProteins.pm
  modules/Bio/EnsEMBL/Production/Pipeline/ProteinFeatures/DeletePathwayXrefs.pm
  modules/Bio/EnsEMBL/Production/Pipeline/ProteinFeatures/DumpInterProXrefs.pm
  modules/Bio/EnsEMBL/Production/Pipeline/ProteinFeatures/EmailReport.pm
  modules/Bio/EnsEMBL/Production/Pipeline/ProteinFeatures/FetchFile.pm
  modules/Bio/EnsEMBL/Production/Pipeline/ProteinFeatures/InterProScan.pm
  modules/Bio/EnsEMBL/Production/Pipeline/ProteinFeatures/InterProScanPrograms.pm
  modules/Bio/EnsEMBL/Production/Pipeline/ProteinFeatures/InterProScanVersionCheck.pm
  modules/Bio/EnsEMBL/Production/Pipeline/ProteinFeatures/LoadChecksums.pm
  modules/Bio/EnsEMBL/Production/Pipeline/ProteinFeatures/LoadUniParc.pm
  modules/Bio/EnsEMBL/Production/Pipeline/ProteinFeatures/LoadUniProt.pm
  modules/Bio/EnsEMBL/Production/Pipeline/ProteinFeatures/PartitionByChecksum.pm
  modules/Bio/EnsEMBL/Production/Pipeline/ProteinFeatures/StoreGoXrefs.pm
  modules/Bio/EnsEMBL/Production/Pipeline/ProteinFeatures/StoreProteinFeatures.pm
Labels: enhancement
