Repository Ensembl/ensembl-production, pull requests merged in 2022-02, with the labels that each got.

#648 New script to create symlinks under the misc directory for some speci…
  scripts/py/regulation_ftp_symlinks.py
Labels: enhancement

#651 Fix package name for renamed parsers
  modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/Parser/RefSeqDatabaseParser.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Xrefs/Parser/UniProtDatabaseParser.pm
Labels: bugfix

#653 Updated path to expected new dirs on CODON.
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_non_vertebrates_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_vertebrates_conf.pm
Labels: bugfix, enhancement

#652 Feature/alphafold script
  scripts/py/alphafoldUpdate.py
Labels: enhancement
