Repository Ensembl/ensembl-production, pull requests merged in 2022-05, with the labels that each got.

#668 canonical flag added to json dump
  modules/Bio/EnsEMBL/Production/Pipeline/JSON/genes_schema.json
Labels: enhancement

#671 Release/107
  modules/Bio/EnsEMBL/Production/Pipeline/JSON/genes_schema.json
  modules/Bio/EnsEMBL/Production/Search/EBeyeGenomeWrapper.pm
Labels: bau

#672 Bugfix/search default eg version
  modules/Bio/EnsEMBL/Production/Search/GenomeFetcher.pm
Labels: bugfix

#675 Updated DBCopy default target api url.
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/CopyDatabaseDBA_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DbCopy_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/OLSLoad_conf.pm
Labels: bau

#677 Use production-tools resources to connect to DB e.g. mysqlclient inst…
  scripts/py/regulation_ftp_symlinks.py
Labels: bugfix, enhancement

#680 Report fix applied on 106
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FileDump_conf.pm
Labels: bugfix

#679 Report fix applied on 106
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FileDump_conf.pm
Labels: bugfix
