Repository Ensembl/ensembl-production, pull requests merged in 2023-11, with the labels that each got.

#841 Report from main
  modules/Bio/EnsEMBL/Production/Pipeline/Common/Gzip.pm
  modules/Bio/EnsEMBL/Production/Pipeline/FileDump/Xref_TSV.pm
  modules/Bio/EnsEMBL/Production/Pipeline/Flatfile/DumpFile.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/DumpCore_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/FileDumpMySQL_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/TSV/DumpFile.pm
  modules/Bio/EnsEMBL/Production/Pipeline/TSV/DumpFileEna.pm
  modules/Bio/EnsEMBL/Production/Pipeline/TSV/DumpFileMetadata.pm
  modules/Bio/EnsEMBL/Production/Pipeline/TSV/DumpFileXref.pm
Labels: bugfix, enhancement

#845 Fix for "scalar on reference"
  modules/Bio/EnsEMBL/Production/Pipeline/AlphaFold/InsertProteinFeatures.pm
Labels: bugfix

#849 Update/mvp checksum
  modules/Bio/EnsEMBL/Production/Pipeline/Checksum/CreateURI.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ChecksumGenerator_conf.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/ChecksumLoader_conf.pm
  src/python/ensembl/production/hive/ensembl_genome_metadata/ChecksumTransfer.py
Labels: enhancement

#846 Moved from LevelDB to KyotoCabinet
  .travis.yml
  cpanfile
  modules/Bio/EnsEMBL/Production/Pipeline/AlphaFold/CreateAlphaDB.pm
  modules/Bio/EnsEMBL/Production/Pipeline/AlphaFold/CreateUniparcDB.pm
  modules/Bio/EnsEMBL/Production/Pipeline/AlphaFold/InsertProteinFeatures.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/AlphaDBImport_conf.pm
  travisci/kyotocabinet-perl-1.20.tar.gz
Labels: bugfix

#855 Integrate GIFTS
  modules/Bio/EnsEMBL/Production/Pipeline/AlphaFold/InsertProteinFeatures.pm
Labels: enhancement

#857 Main
  modules/Bio/EnsEMBL/Production/Pipeline/AlphaFold/InsertProteinFeatures.pm
  modules/Bio/EnsEMBL/Production/Pipeline/PipeConfig/EarlyDumps_conf.pm
Labels: enhancement
